# Generated by Django 6.0.6 on 2026-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_salary_year_alter_salary_salary_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
